name: pytorch-template
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.13=haa1d7c7_1
  - readline=8.2=h5eee18b_0
  - setuptools=65.4.0=py38h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - antlr4-python3-runtime==4.9.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorlog==6.7.0
    - commonmark==0.9.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - fonttools==4.38.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - hydra-colorlog==1.2.0
    - hydra-core==1.2.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - numpy==1.23.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - packaging==21.3
    - pathtools==0.1.2
    - pillow==9.3.0
    - prefetch-generator==1.0.1
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - sentry-sdk==1.10.1
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - six==1.16.0
    - sklearn==0.0
    - smmap==5.0.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - torch==1.13.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wandb==0.13.4
    - werkzeug==2.2.2
    - zipp==3.10.0
prefix: /home/comp/zmzhang/anaconda3/envs/pytorch-template
